### ISSUE TITLE
Bug: Social Media Icons in Footer

### ISSUE THREAD

**Issue by avishj** [CodeChefVIT/Web-Apps-Website-20#20]
![image](https://user-images.githubusercontent.com/58023328/91895788-6ec71d00-ecb5-11ea-8d90-1197958db6bf.png)

On hovering over the social media icons, a blue line protrudes through the icon
OS: Win 10 LTSC
Broswer: Chromium 84.0.4131.0 (Dev) (64bit)

**Comment by lio2011** [comment]
it has been taken care of in the updated code
